### The concept of transposed convolution
### Task 1:
    * Define an input tensor and a kernel
    * Compute the transposed convolution per hand
    * Check that your computations are correct using ConvTranspose2d 

In [66]:
import torch
import torch.nn as nn



###########################################################
## TODO: Define the input tensor # (batch_size, input_channels, input_height, input_width)
input_tensor = None
print(input_tensor.shape)
input_tensor = input_tensor.unsqueeze(0).unsqueeze(0)
print(input_tensor)

## TODO: Define the kernel tensor
kernel_tensor = None

## TODO: Check the values of the transposed convolution
# Define the transposed convolution layer
transposed_conv = nn.ConvTranspose2d(1, 1, kernel_size=2, stride=2, padding=0, output_padding=0,bias=False)
# (input_channels, output_channels, kernel_size, stride, padding, output_padding)
transposed_conv.weight = nn.Parameter(kernel_tensor, dtype=torch.float32)
print(transposed_conv.weight)
# Perform the transposed convolution
output_tensor = transposed_conv(input_tensor)

# Print the shape of the output tensor
print(output_tensor.shape)
print(output_tensor)

torch.Size([2, 2])
tensor([[[[0., 1.],
          [2., 3.]]]])
Parameter containing:
tensor([[[[0., 1.],
          [2., 3.]]]], requires_grad=True)
torch.Size([1, 1, 2, 2])
tensor([[[[0., 2.],
          [2., 0.]]]], grad_fn=<ConvolutionBackward0>)
